apiVersion: v1
kind: Namespace
metadata:
  name: jf-web
---
# Hardened NGINX Web Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jf-web-deployment
  namespace: jf-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jf-web
  template:
    metadata:
      labels:
        app: jf-web
    spec:
      containers:
      - name: web
        image: ghcr.io/shavedcloaca/jessamine-farm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        # Mount writable scratch spaces for NGINX
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /var/cache/nginx
        - name: run-volume
          mountPath: /var/run
      # Define temporary in-memory volumes
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
---
# EXPOSED Cluster Routing Service
apiVersion: v1
kind: Service
metadata:
  name: jf-web-service
  namespace: jf-web
spec:
  type: LoadBalancer # This tells k3s to expose this service on the host IP
  selector:
    app: jf-web
  ports:
  - port: 80
    targetPort: 8080